### ISSUE TITLE
fastotv_cpp never compilation failure on debian 11.5

### ISSUE THREAD

**Issue by gabessolo** [fastogt/fastotv_cpp#2]
wwwdata@debian:~/fastotv_cpp/build$ cmake ../
-- PROJECT_VERSION: 1.3.1.8
-- CMAKE_INSTALL_PREFIX: /home/wwwdata/fastotv_cpp/build/install
CMake Error at CMakeLists.txt:81 (INCLUDE):
  INCLUDE could not find load file:

    config

CMake Error at CMakeLists.txt:82 (DEFINE_DEFAULT_DEFINITIONS):
  Unknown CMake command "DEFINE_DEFAULT_DEFINITIONS".

-- Configuring incomplete, errors occurred!
See also "/home/wwwdata/fastotv_cpp/build/CMakeFiles/CMakeOutput.log".

**Comment by topilski** [comment]
git submodule update --init --recursive
